from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton, KeyboardButton, ReplyKeyboardMarkup


registrate_inline_btn = InlineKeyboardButton('Зарегистрироваться', callback_data='reg_btn')
seller_inline_btn = InlineKeyboardButton('Продавец', callback_data='seller_btn')
buyer_inline_btn = InlineKeyboardButton('Покупатель', callback_data='buyer_btn')
recreate_inline_btn = InlineKeyboardButton('Пересоздать', callback_data='rec_btn')
dontrec_inline_btn = InlineKeyboardButton('Продолжить', callback_data='drec_btn')
start_search_btn = InlineKeyboardButton('Начать поиск 🔎', callback_data='start_search')
cancel_search_btn = InlineKeyboardButton('Отменить поиск ❌', callback_data='cancel_search')
like_inline_btn = InlineKeyboardButton('👍', callback_data='plus_btn')
dislike_inline_btn = InlineKeyboardButton('👎', callback_data='minus_btn')
irl_inline_btn = InlineKeyboardButton('Самовывоз', callback_data='irl_btn')
delivery_inline_btn = InlineKeyboardButton('Доставка', callback_data='delivery_btn')
dmater_inline_btn = InlineKeyboardButton('Не важно', callback_data='dmater_btn')
confirm_inline_btn = InlineKeyboardButton('Подтвердить', callback_data='confirm_photo')
cancel_inline_btn = InlineKeyboardButton('Отменить', callback_data='cancel_photo')
done = KeyboardButton('Готово')
search = KeyboardButton('Поиск')
size = KeyboardButton('Изменить размер обуви')
photo = KeyboardButton('Изменить фото')
ancent = KeyboardButton('Поменять анкету')
cancel_btn = KeyboardButton('Отмена')
reg_btn = KeyboardButton('Зарегистрироваться')
stop_btn = KeyboardButton('Стоп')

greet_kb = InlineKeyboardMarkup().add(registrate_inline_btn)
choise_kb = InlineKeyboardMarkup().row(buyer_inline_btn, seller_inline_btn)
rec_or_not_kb = InlineKeyboardMarkup().row(recreate_inline_btn, dontrec_inline_btn)
rate_kb = InlineKeyboardMarkup().row(like_inline_btn, dislike_inline_btn)
search_kb = InlineKeyboardMarkup().row(start_search_btn, cancel_search_btn)
tob_kb = InlineKeyboardMarkup().row(irl_inline_btn, delivery_inline_btn, dmater_inline_btn)
confirm_kb = InlineKeyboardMarkup().row(confirm_inline_btn, cancel_inline_btn)
done_kb = ReplyKeyboardMarkup(resize_keyboard=True).add(done)
seller_menu_kb = ReplyKeyboardMarkup(resize_keyboard=True, row_width=1).row(search, size).row(photo, ancent)
buyer_menu_kb = ReplyKeyboardMarkup(resize_keyboard=True, row_width=2).row(search, size).add(ancent)
cancel_kb = ReplyKeyboardMarkup(resize_keyboard=True).add(cancel_btn)
reg_btn_kb = ReplyKeyboardMarkup(resize_keyboard=True).add(reg_btn)
stop_btn_kb = ReplyKeyboardMarkup(resize_keyboard=True).add(stop_btn)